image: node:latest
variables:
  AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
  AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY

stages:
  - install
  - build
  - test
  - deploy
  
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
    - backend/node_modules/
    - frontend/node_modules/

install:
  stage: install
  script:
    - npm install --unsafe-perm

build-frontend:
  stage: build
  script:
    - cd frontend
    - npm run build
  artifacts:    
      paths:
         - frontend/build/
      expire_in: 1 hour

test-frontend:
  stage: test
  script:
    - cd frontend
    - npm run test

deploy-frontend:  
   image: python:latest  
   stage: deploy
   only:
    - master
   script:    
      - cd frontend
      - pip install awscli
      - aws s3 sync ./build s3://$FRONTEND_BUCKET_NAME

test-backend:
  stage: test
  script:
    - cd backend
    - npm run test

deploy-backend:
   image: python:latest
   stage: deploy
   only:
    - master
   script:
      - cd backend
      - pip install awsebcli
      - yes n | eb init ruth --region us-west-2
      - eb deploy $BACKEND_EB_ENV_NAME
