version: '3'
services: 
  database:
    image: "postgres:10-alpine"
    environment:
      - POSTGRES_DB=ruth
      - POSTGRES_USER=ruth
      - POSTGRES_PASSWORD=ruth
    ports:
      - "15432:5432"
    volumes:
      - ./db-data:/var/lib/postgresql/data
