version: 2.1
jobs:
  build:
    working_directory: ~/ruth
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          keys:
            - deps-{{ checksum "package-lock.json" }}
            - deps-frontend-{{ checksum "frontend/package-lock.json" }}
            - deps-backend-{{ checksum "backend/package-lock.json" }}
      - run:
          name: install-npm-wee
          command: npm install
      - save_cache:
          key: deps-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - save_cache:
          key: deps-frontend-{{ checksum "frontend/package-lock.json" }}
          paths:
            - ./frontend/node_modules
      - save_cache:
          key: deps-backend-{{ checksum "backend/package-lock.json" }}
          paths:
            - ./backend/node_modules
      - run:
          name: test
          command: npm test
